version: "3.3"

services:
  random_schedule:
    image: random_schedule:latest
    container_name: random_schedule
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      PYTHONUNBUFFERED: 1
    secrets:
      - tg_key

secrets:
  tg_key:
    file: ./tg.key  # file with your bot tg key

